defaults: &defaults
  roles: ['admin', 'manager', 'distirbutor', 'user']
  fb:
    app_id: 201952163262122
    secret_key: f8ba6fee165410f4c97f336ca5ca20af

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  fb:
    app_id: 201952163262122
    secret_key: f8ba6fee165410f4c97f336ca5ca20af
